# coding: utf-8

"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from transparenc_sdk.models.grant_type_enum import GrantTypeEnum

class TestGrantTypeEnum(unittest.TestCase):
    """GrantTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantTypeEnum(self):
        """Test GrantTypeEnum"""
        # inst = GrantTypeEnum()

if __name__ == '__main__':
    unittest.main()
