# coding: utf-8

"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: v1.0.0+build49
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from transparenc_sdk.api.o_auth_device_flow_api import OAuthDeviceFlowApi


class TestOAuthDeviceFlowApi(unittest.TestCase):
    """OAuthDeviceFlowApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthDeviceFlowApi()

    def tearDown(self) -> None:
        pass

    def test_v1_oauth_device_authorization_create(self) -> None:
        """Test case for v1_oauth_device_authorization_create

        Start device authorization (Device Code Flow)
        """
        pass

    def test_v1_oauth_token_create(self) -> None:
        """Test case for v1_oauth_token_create

        Device polls for token
        """
        pass


if __name__ == '__main__':
    unittest.main()
