# coding: utf-8

"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: v1.0.0+build51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from transparenc_sdk.models.device_token_response import DeviceTokenResponse

class TestDeviceTokenResponse(unittest.TestCase):
    """DeviceTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceTokenResponse:
        """Test DeviceTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceTokenResponse`
        """
        model = DeviceTokenResponse()
        if include_optional:
            return DeviceTokenResponse(
                access_token = '',
                token_type = 'Bearer',
                expires_in = 56,
                refresh_token = '',
                scope = ''
            )
        else:
            return DeviceTokenResponse(
                access_token = '',
                expires_in = 56,
        )
        """

    def testDeviceTokenResponse(self):
        """Test DeviceTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
