# coding: utf-8

"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.device_authorization_request import DeviceAuthorizationRequest

class TestDeviceAuthorizationRequest(unittest.TestCase):
    """DeviceAuthorizationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceAuthorizationRequest:
        """Test DeviceAuthorizationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceAuthorizationRequest`
        """
        model = DeviceAuthorizationRequest()
        if include_optional:
            return DeviceAuthorizationRequest(
                client_id = '',
                scope = '',
                device_type = '',
                device_os = ''
            )
        else:
            return DeviceAuthorizationRequest(
                client_id = '',
                device_type = '',
                device_os = '',
        )
        """

    def testDeviceAuthorizationRequest(self):
        """Test DeviceAuthorizationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
