# coding: utf-8

"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: v1.0.0+build51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from transparenc_sdk.models.device_authorization_response import DeviceAuthorizationResponse

class TestDeviceAuthorizationResponse(unittest.TestCase):
    """DeviceAuthorizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceAuthorizationResponse:
        """Test DeviceAuthorizationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceAuthorizationResponse`
        """
        model = DeviceAuthorizationResponse()
        if include_optional:
            return DeviceAuthorizationResponse(
                device_code = '',
                user_code = '',
                verification_uri = '',
                expires_in = 56,
                interval = 56
            )
        else:
            return DeviceAuthorizationResponse(
                device_code = '',
                user_code = '',
                verification_uri = '',
                expires_in = 56,
                interval = 56,
        )
        """

    def testDeviceAuthorizationResponse(self):
        """Test DeviceAuthorizationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
