//
// OAuthDeviceFlowAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class OAuthDeviceFlowAPI {

    /**
     Start device authorization (Device Code Flow)
     
     - parameter clientId: (form)  
     - parameter deviceType: (form)  
     - parameter deviceOs: (form)  
     - parameter scope: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeviceAuthorizationResponse
     */
    open class func v1OauthDeviceAuthorizationCreate(clientId: String, deviceType: String, deviceOs: String, scope: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> DeviceAuthorizationResponse {
        return try await v1OauthDeviceAuthorizationCreateWithRequestBuilder(clientId: clientId, deviceType: deviceType, deviceOs: deviceOs, scope: scope, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start device authorization (Device Code Flow)
     - POST /api/v1/oauth/device-authorization/
     - Device posts its metadata and receives a device_code and user_code.
     - parameter clientId: (form)  
     - parameter deviceType: (form)  
     - parameter deviceOs: (form)  
     - parameter scope: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeviceAuthorizationResponse> 
     */
    open class func v1OauthDeviceAuthorizationCreateWithRequestBuilder(clientId: String, deviceType: String, deviceOs: String, scope: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<DeviceAuthorizationResponse> {
        let localVariablePath = "/api/v1/oauth/device-authorization/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "client_id": clientId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "scope": scope?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "device_type": deviceType.asParameter(codableHelper: apiConfiguration.codableHelper),
            "device_os": deviceOs.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeviceAuthorizationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Device polls for token
     
     - parameter grantType: (form)  
     - parameter deviceCode: (form)  
     - parameter clientId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeviceTokenResponse
     */
    open class func v1OauthTokenCreate(grantType: GrantTypeEnum, deviceCode: String, clientId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> DeviceTokenResponse {
        return try await v1OauthTokenCreateWithRequestBuilder(grantType: grantType, deviceCode: deviceCode, clientId: clientId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Device polls for token
     - POST /api/v1/oauth/token
     - Device polls for token
     - parameter grantType: (form)  
     - parameter deviceCode: (form)  
     - parameter clientId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeviceTokenResponse> 
     */
    open class func v1OauthTokenCreateWithRequestBuilder(grantType: GrantTypeEnum, deviceCode: String, clientId: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<DeviceTokenResponse> {
        let localVariablePath = "/api/v1/oauth/token"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "grant_type": grantType.asParameter(codableHelper: apiConfiguration.codableHelper),
            "device_code": deviceCode.asParameter(codableHelper: apiConfiguration.codableHelper),
            "client_id": clientId.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeviceTokenResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
