//
// OAuthDeviceFlowAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class OAuthDeviceFlowAPI {

    /**
     Start device authorization (Device Code Flow)
     
     - parameter deviceAuthorizationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeviceAuthorizationResponse
     */
    open class func v1OauthDeviceAuthorizationCreate(deviceAuthorizationRequest: DeviceAuthorizationRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> DeviceAuthorizationResponse {
        return try await v1OauthDeviceAuthorizationCreateWithRequestBuilder(deviceAuthorizationRequest: deviceAuthorizationRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Start device authorization (Device Code Flow)
     - POST /api/v1/oauth/device-authorization/
     - Device posts its metadata and receives a device_code and user_code.
     - parameter deviceAuthorizationRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeviceAuthorizationResponse> 
     */
    open class func v1OauthDeviceAuthorizationCreateWithRequestBuilder(deviceAuthorizationRequest: DeviceAuthorizationRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<DeviceAuthorizationResponse> {
        let localVariablePath = "/api/v1/oauth/device-authorization/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: deviceAuthorizationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeviceAuthorizationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Device polls for token
     
     - parameter deviceTokenRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: DeviceAuthorizationResponse
     */
    open class func v1OauthTokenCreate(deviceTokenRequest: DeviceTokenRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> DeviceAuthorizationResponse {
        return try await v1OauthTokenCreateWithRequestBuilder(deviceTokenRequest: deviceTokenRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Device polls for token
     - POST /api/v1/oauth/token
     - Device polls for token
     - parameter deviceTokenRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<DeviceAuthorizationResponse> 
     */
    open class func v1OauthTokenCreateWithRequestBuilder(deviceTokenRequest: DeviceTokenRequest, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<DeviceAuthorizationResponse> {
        let localVariablePath = "/api/v1/oauth/token"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: deviceTokenRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DeviceAuthorizationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
