//
// DeviceAuthorizationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthorizationResponse: Sendable, Codable, Hashable {

    public var deviceCode: String
    public var userCode: String
    public var verificationUri: String
    public var expiresIn: Int
    public var interval: Int

    public init(deviceCode: String, userCode: String, verificationUri: String, expiresIn: Int, interval: Int) {
        self.deviceCode = deviceCode
        self.userCode = userCode
        self.verificationUri = verificationUri
        self.expiresIn = expiresIn
        self.interval = interval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceCode = "device_code"
        case userCode = "user_code"
        case verificationUri = "verification_uri"
        case expiresIn = "expires_in"
        case interval
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deviceCode, forKey: .deviceCode)
        try container.encode(userCode, forKey: .userCode)
        try container.encode(verificationUri, forKey: .verificationUri)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encode(interval, forKey: .interval)
    }
}

