//
// DeviceTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceTokenRequest: Sendable, Codable, Hashable {

    public static let deviceCodeRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public static let clientIdRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public var grantType: GrantTypeEnum
    public var deviceCode: String
    public var clientId: String?

    public init(grantType: GrantTypeEnum, deviceCode: String, clientId: String? = nil) {
        self.grantType = grantType
        self.deviceCode = deviceCode
        self.clientId = clientId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case grantType = "grant_type"
        case deviceCode = "device_code"
        case clientId = "client_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(grantType, forKey: .grantType)
        try container.encode(deviceCode, forKey: .deviceCode)
        try container.encodeIfPresent(clientId, forKey: .clientId)
    }
}

