//
// DeviceAuthorizationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeviceAuthorizationRequest: Sendable, Codable, Hashable {

    public var clientId: String
    public var scope: String?
    public var deviceType: String
    public var deviceOs: String

    public init(clientId: String, scope: String? = nil, deviceType: String, deviceOs: String) {
        self.clientId = clientId
        self.scope = scope
        self.deviceType = deviceType
        self.deviceOs = deviceOs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case scope
        case deviceType = "device_type"
        case deviceOs = "device_os"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encode(deviceType, forKey: .deviceType)
        try container.encode(deviceOs, forKey: .deviceOs)
    }
}

