# coding: utf-8

# flake8: noqa
"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: v1.0.0+build50
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from transparenc_sdk.models.device_authorization_response import DeviceAuthorizationResponse
from transparenc_sdk.models.device_token_response import DeviceTokenResponse
from transparenc_sdk.models.grant_type_enum import GrantTypeEnum

