# coding: utf-8

"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: v1.0.0+build51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GrantTypeEnum(str, Enum):
    """
    * `refresh_token` - refresh_token * `urn:ietf:params:oauth:grant-type:device_code` - urn:ietf:params:oauth:grant-type:device_code
    """

    """
    allowed enum values
    """
    REFRESH_TOKEN = 'refresh_token'
    URN_COLON_IETF_COLON_PARAMS_COLON_OAUTH_COLON_GRANT_MINUS_TYPE_COLON_DEVICE_CODE = 'urn:ietf:params:oauth:grant-type:device_code'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GrantTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


