# coding: utf-8

# flake8: noqa

"""
    My Device API

    User, device, and OAuth APIs

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "OAuthDeviceFlowApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "DeviceAuthorizationRequest",
    "DeviceAuthorizationResponse",
    "DeviceTokenRequest",
    "GrantTypeEnum",
]

# import apis into sdk package
from openapi_client.api.o_auth_device_flow_api import OAuthDeviceFlowApi as OAuthDeviceFlowApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.device_authorization_request import DeviceAuthorizationRequest as DeviceAuthorizationRequest
from openapi_client.models.device_authorization_response import DeviceAuthorizationResponse as DeviceAuthorizationResponse
from openapi_client.models.device_token_request import DeviceTokenRequest as DeviceTokenRequest
from openapi_client.models.grant_type_enum import GrantTypeEnum as GrantTypeEnum

