name: OpenAPIClient
targets:
  OpenAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: v1.0.0+build52
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
